pipeline
{
agent any
		tools { 
			maven 'M2_HOME' 
			jdk 'java_home'
		      }
		  environment {
          	//Email_Recepient = 'a@b.com;x@y.com';
          	Email_Recepient = 'vaibhav.sharma81@gmail.com';
          	//Cucumber_Tag_Smoke='@smoke';
            }
             
stages
{
	stage('Compile Stage')
	{
		steps
		{
			bat 'mvn clean compile'
			findText(textFinders: [textFinder(regexp:'^FAILED', alsoCheckConsoleOutput: true, buildResult: 'FAILURE')])
		}
	}
	stage('Test Stage')
	{
		steps
		{
			bat 'mvn verify'
			//bat	"mvn test -Dcucumber.filter.tags=${Cucumber_Tag_Login}"
					
			findText(textFinders: [
  			textFinder(regexp: '^FAILED', alsoCheckConsoleOutput: true, buildResult: 'FAILURE'),
 			textFinder(regexp: 'AssertionError', alsoCheckConsoleOutput: true, buildResult: 'FAILURE'),
 			textFinder(regexp: 'NoSuchElementException', alsoCheckConsoleOutput: true, buildResult: 'FAILURE'),
 			textFinder(regexp: 'No features present in test execution.', alsoCheckConsoleOutput: true, buildResult: 'FAILURE'),	
 			])
		}
	}
	stage ('Report')
	{
		steps 
		{
		cucumber reportTitle: 'SalesForce Report',
        fileIncludePattern: 'target/cucumber-reports/CucumberTestReport.json', 
        sortingMethod: 'ALPHABETICAL',
      	trendsLimit: 100            
		}
	}
	   }

	post 
	{
       
       success {
           emailext ( attachLog: false,
	       attachmentsPattern: '**/ExtentPdf.pdf',
	       to: "${Email_Recepient}", 
	       subject: "Passed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'", 
	       //body: readFile("cucumber-reports-with-handlebars/featuresOverview.html"), 
	       // body: readFile("target/overview-features.html"),
	       body: '''${SCRIPT, template="groovy-html.template"}''',
	       mimeType: 'text/html');
	       }
       failure {
            emailext ( attachLog: false,
	        attachmentsPattern: '**/ExtentPdf.pdf',
	       to: "${Email_Recepient}", 
	       subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'", 
	       //body: readFile("cucumber-reports-with-handlebars/featuresOverview.html"), 
		   body: '''${SCRIPT, template="groovy-html.template"}''',
	       mimeType: 'text/html');
        	}
        	
       }
}
